# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-31 19:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Path',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_path', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_name', models.CharField(max_length=100)),
                ('m_address', models.CharField(max_length=100)),
                ('m_score', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_time', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='path',
            name='m_route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_gen.Route'),
        ),
    ]
